language: ruby
rvm:
  - 2.2.1
script: bundle exec rspec
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp config/database-sample.yml.travis config/database.yml
addons:
  postgresql: "9.3"
